// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: demo.proto

package prx.proto.demo;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MPCInteger32OrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.MPCInteger32)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 i32 = 1;</code>
     */
    int getI32();
  }
  /**
   * Protobuf type {@code demo.MPCInteger32}
   */
  public  static final class MPCInteger32 extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.MPCInteger32)
      MPCInteger32OrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MPCInteger32.newBuilder() to construct.
    private MPCInteger32(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPCInteger32() {
      i32_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPCInteger32(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              i32_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prx.proto.demo.Demo.internal_static_demo_MPCInteger32_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prx.proto.demo.Demo.internal_static_demo_MPCInteger32_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              prx.proto.demo.Demo.MPCInteger32.class, prx.proto.demo.Demo.MPCInteger32.Builder.class);
    }

    public static final int I32_FIELD_NUMBER = 1;
    private int i32_;
    /**
     * <code>int32 i32 = 1;</code>
     */
    public int getI32() {
      return i32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (i32_ != 0) {
        output.writeInt32(1, i32_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, i32_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof prx.proto.demo.Demo.MPCInteger32)) {
        return super.equals(obj);
      }
      prx.proto.demo.Demo.MPCInteger32 other = (prx.proto.demo.Demo.MPCInteger32) obj;

      boolean result = true;
      result = result && (getI32()
          == other.getI32());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCInteger32 parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(prx.proto.demo.Demo.MPCInteger32 prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.MPCInteger32}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.MPCInteger32)
        prx.proto.demo.Demo.MPCInteger32OrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prx.proto.demo.Demo.internal_static_demo_MPCInteger32_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prx.proto.demo.Demo.internal_static_demo_MPCInteger32_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                prx.proto.demo.Demo.MPCInteger32.class, prx.proto.demo.Demo.MPCInteger32.Builder.class);
      }

      // Construct using prx.proto.demo.Demo.MPCInteger32.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        i32_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prx.proto.demo.Demo.internal_static_demo_MPCInteger32_descriptor;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCInteger32 getDefaultInstanceForType() {
        return prx.proto.demo.Demo.MPCInteger32.getDefaultInstance();
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCInteger32 build() {
        prx.proto.demo.Demo.MPCInteger32 result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCInteger32 buildPartial() {
        prx.proto.demo.Demo.MPCInteger32 result = new prx.proto.demo.Demo.MPCInteger32(this);
        result.i32_ = i32_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prx.proto.demo.Demo.MPCInteger32) {
          return mergeFrom((prx.proto.demo.Demo.MPCInteger32)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(prx.proto.demo.Demo.MPCInteger32 other) {
        if (other == prx.proto.demo.Demo.MPCInteger32.getDefaultInstance()) return this;
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        prx.proto.demo.Demo.MPCInteger32 parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (prx.proto.demo.Demo.MPCInteger32) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 1;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 1;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.MPCInteger32)
    }

    // @@protoc_insertion_point(class_scope:demo.MPCInteger32)
    private static final prx.proto.demo.Demo.MPCInteger32 DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new prx.proto.demo.Demo.MPCInteger32();
    }

    public static prx.proto.demo.Demo.MPCInteger32 getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPCInteger32>
        PARSER = new com.google.protobuf.AbstractParser<MPCInteger32>() {
      @java.lang.Override
      public MPCInteger32 parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPCInteger32(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPCInteger32> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPCInteger32> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public prx.proto.demo.Demo.MPCInteger32 getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface MPCFloatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.MPCFloat)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float f = 1;</code>
     */
    float getF();
  }
  /**
   * Protobuf type {@code demo.MPCFloat}
   */
  public  static final class MPCFloat extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.MPCFloat)
      MPCFloatOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MPCFloat.newBuilder() to construct.
    private MPCFloat(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MPCFloat() {
      f_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MPCFloat(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              f_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prx.proto.demo.Demo.internal_static_demo_MPCFloat_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prx.proto.demo.Demo.internal_static_demo_MPCFloat_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              prx.proto.demo.Demo.MPCFloat.class, prx.proto.demo.Demo.MPCFloat.Builder.class);
    }

    public static final int F_FIELD_NUMBER = 1;
    private float f_;
    /**
     * <code>float f = 1;</code>
     */
    public float getF() {
      return f_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (f_ != 0F) {
        output.writeFloat(1, f_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (f_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, f_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof prx.proto.demo.Demo.MPCFloat)) {
        return super.equals(obj);
      }
      prx.proto.demo.Demo.MPCFloat other = (prx.proto.demo.Demo.MPCFloat) obj;

      boolean result = true;
      result = result && (
          java.lang.Float.floatToIntBits(getF())
          == java.lang.Float.floatToIntBits(
              other.getF()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getF());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCFloat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCFloat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.MPCFloat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(prx.proto.demo.Demo.MPCFloat prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.MPCFloat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.MPCFloat)
        prx.proto.demo.Demo.MPCFloatOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prx.proto.demo.Demo.internal_static_demo_MPCFloat_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prx.proto.demo.Demo.internal_static_demo_MPCFloat_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                prx.proto.demo.Demo.MPCFloat.class, prx.proto.demo.Demo.MPCFloat.Builder.class);
      }

      // Construct using prx.proto.demo.Demo.MPCFloat.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        f_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prx.proto.demo.Demo.internal_static_demo_MPCFloat_descriptor;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCFloat getDefaultInstanceForType() {
        return prx.proto.demo.Demo.MPCFloat.getDefaultInstance();
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCFloat build() {
        prx.proto.demo.Demo.MPCFloat result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.MPCFloat buildPartial() {
        prx.proto.demo.Demo.MPCFloat result = new prx.proto.demo.Demo.MPCFloat(this);
        result.f_ = f_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prx.proto.demo.Demo.MPCFloat) {
          return mergeFrom((prx.proto.demo.Demo.MPCFloat)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(prx.proto.demo.Demo.MPCFloat other) {
        if (other == prx.proto.demo.Demo.MPCFloat.getDefaultInstance()) return this;
        if (other.getF() != 0F) {
          setF(other.getF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        prx.proto.demo.Demo.MPCFloat parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (prx.proto.demo.Demo.MPCFloat) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float f_ ;
      /**
       * <code>float f = 1;</code>
       */
      public float getF() {
        return f_;
      }
      /**
       * <code>float f = 1;</code>
       */
      public Builder setF(float value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float f = 1;</code>
       */
      public Builder clearF() {
        
        f_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.MPCFloat)
    }

    // @@protoc_insertion_point(class_scope:demo.MPCFloat)
    private static final prx.proto.demo.Demo.MPCFloat DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new prx.proto.demo.Demo.MPCFloat();
    }

    public static prx.proto.demo.Demo.MPCFloat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MPCFloat>
        PARSER = new com.google.protobuf.AbstractParser<MPCFloat>() {
      @java.lang.Override
      public MPCFloat parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MPCFloat(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MPCFloat> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<MPCFloat> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public prx.proto.demo.Demo.MPCFloat getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FooOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Foo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    boolean hasMpcI32();
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    prx.proto.demo.Demo.MPCInteger32 getMpcI32();
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder();

    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    boolean hasMpcF();
    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    prx.proto.demo.Demo.MPCFloat getMpcF();
    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    prx.proto.demo.Demo.MPCFloatOrBuilder getMpcFOrBuilder();

    /**
     * <code>int32 i32 = 3;</code>
     */
    int getI32();

    /**
     * <code>float f = 4;</code>
     */
    float getF();
  }
  /**
   * Protobuf type {@code demo.Foo}
   */
  public  static final class Foo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Foo)
      FooOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Foo.newBuilder() to construct.
    private Foo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Foo() {
      i32_ = 0;
      f_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Foo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              prx.proto.demo.Demo.MPCInteger32.Builder subBuilder = null;
              if (mpcI32_ != null) {
                subBuilder = mpcI32_.toBuilder();
              }
              mpcI32_ = input.readMessage(prx.proto.demo.Demo.MPCInteger32.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mpcI32_);
                mpcI32_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              prx.proto.demo.Demo.MPCFloat.Builder subBuilder = null;
              if (mpcF_ != null) {
                subBuilder = mpcF_.toBuilder();
              }
              mpcF_ = input.readMessage(prx.proto.demo.Demo.MPCFloat.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mpcF_);
                mpcF_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              i32_ = input.readInt32();
              break;
            }
            case 37: {

              f_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prx.proto.demo.Demo.internal_static_demo_Foo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prx.proto.demo.Demo.internal_static_demo_Foo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              prx.proto.demo.Demo.Foo.class, prx.proto.demo.Demo.Foo.Builder.class);
    }

    public static final int MPC_I32_FIELD_NUMBER = 1;
    private prx.proto.demo.Demo.MPCInteger32 mpcI32_;
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    public boolean hasMpcI32() {
      return mpcI32_ != null;
    }
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    public prx.proto.demo.Demo.MPCInteger32 getMpcI32() {
      return mpcI32_ == null ? prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
    }
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
     */
    public prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder() {
      return getMpcI32();
    }

    public static final int MPC_F_FIELD_NUMBER = 2;
    private prx.proto.demo.Demo.MPCFloat mpcF_;
    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    public boolean hasMpcF() {
      return mpcF_ != null;
    }
    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    public prx.proto.demo.Demo.MPCFloat getMpcF() {
      return mpcF_ == null ? prx.proto.demo.Demo.MPCFloat.getDefaultInstance() : mpcF_;
    }
    /**
     * <code>.demo.MPCFloat mpc_f = 2;</code>
     */
    public prx.proto.demo.Demo.MPCFloatOrBuilder getMpcFOrBuilder() {
      return getMpcF();
    }

    public static final int I32_FIELD_NUMBER = 3;
    private int i32_;
    /**
     * <code>int32 i32 = 3;</code>
     */
    public int getI32() {
      return i32_;
    }

    public static final int F_FIELD_NUMBER = 4;
    private float f_;
    /**
     * <code>float f = 4;</code>
     */
    public float getF() {
      return f_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (mpcI32_ != null) {
        output.writeMessage(1, getMpcI32());
      }
      if (mpcF_ != null) {
        output.writeMessage(2, getMpcF());
      }
      if (i32_ != 0) {
        output.writeInt32(3, i32_);
      }
      if (f_ != 0F) {
        output.writeFloat(4, f_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (mpcI32_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMpcI32());
      }
      if (mpcF_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMpcF());
      }
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, i32_);
      }
      if (f_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, f_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof prx.proto.demo.Demo.Foo)) {
        return super.equals(obj);
      }
      prx.proto.demo.Demo.Foo other = (prx.proto.demo.Demo.Foo) obj;

      boolean result = true;
      result = result && (hasMpcI32() == other.hasMpcI32());
      if (hasMpcI32()) {
        result = result && getMpcI32()
            .equals(other.getMpcI32());
      }
      result = result && (hasMpcF() == other.hasMpcF());
      if (hasMpcF()) {
        result = result && getMpcF()
            .equals(other.getMpcF());
      }
      result = result && (getI32()
          == other.getI32());
      result = result && (
          java.lang.Float.floatToIntBits(getF())
          == java.lang.Float.floatToIntBits(
              other.getF()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMpcI32()) {
        hash = (37 * hash) + MPC_I32_FIELD_NUMBER;
        hash = (53 * hash) + getMpcI32().hashCode();
      }
      if (hasMpcF()) {
        hash = (37 * hash) + MPC_F_FIELD_NUMBER;
        hash = (53 * hash) + getMpcF().hashCode();
      }
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getF());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static prx.proto.demo.Demo.Foo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Foo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Foo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Foo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(prx.proto.demo.Demo.Foo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Foo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Foo)
        prx.proto.demo.Demo.FooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prx.proto.demo.Demo.internal_static_demo_Foo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prx.proto.demo.Demo.internal_static_demo_Foo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                prx.proto.demo.Demo.Foo.class, prx.proto.demo.Demo.Foo.Builder.class);
      }

      // Construct using prx.proto.demo.Demo.Foo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (mpcI32Builder_ == null) {
          mpcI32_ = null;
        } else {
          mpcI32_ = null;
          mpcI32Builder_ = null;
        }
        if (mpcFBuilder_ == null) {
          mpcF_ = null;
        } else {
          mpcF_ = null;
          mpcFBuilder_ = null;
        }
        i32_ = 0;

        f_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prx.proto.demo.Demo.internal_static_demo_Foo_descriptor;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Foo getDefaultInstanceForType() {
        return prx.proto.demo.Demo.Foo.getDefaultInstance();
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Foo build() {
        prx.proto.demo.Demo.Foo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Foo buildPartial() {
        prx.proto.demo.Demo.Foo result = new prx.proto.demo.Demo.Foo(this);
        if (mpcI32Builder_ == null) {
          result.mpcI32_ = mpcI32_;
        } else {
          result.mpcI32_ = mpcI32Builder_.build();
        }
        if (mpcFBuilder_ == null) {
          result.mpcF_ = mpcF_;
        } else {
          result.mpcF_ = mpcFBuilder_.build();
        }
        result.i32_ = i32_;
        result.f_ = f_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prx.proto.demo.Demo.Foo) {
          return mergeFrom((prx.proto.demo.Demo.Foo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(prx.proto.demo.Demo.Foo other) {
        if (other == prx.proto.demo.Demo.Foo.getDefaultInstance()) return this;
        if (other.hasMpcI32()) {
          mergeMpcI32(other.getMpcI32());
        }
        if (other.hasMpcF()) {
          mergeMpcF(other.getMpcF());
        }
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        if (other.getF() != 0F) {
          setF(other.getF());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        prx.proto.demo.Demo.Foo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (prx.proto.demo.Demo.Foo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private prx.proto.demo.Demo.MPCInteger32 mpcI32_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder> mpcI32Builder_;
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public boolean hasMpcI32() {
        return mpcI32Builder_ != null || mpcI32_ != null;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32 getMpcI32() {
        if (mpcI32Builder_ == null) {
          return mpcI32_ == null ? prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
        } else {
          return mpcI32Builder_.getMessage();
        }
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public Builder setMpcI32(prx.proto.demo.Demo.MPCInteger32 value) {
        if (mpcI32Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mpcI32_ = value;
          onChanged();
        } else {
          mpcI32Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public Builder setMpcI32(
          prx.proto.demo.Demo.MPCInteger32.Builder builderForValue) {
        if (mpcI32Builder_ == null) {
          mpcI32_ = builderForValue.build();
          onChanged();
        } else {
          mpcI32Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public Builder mergeMpcI32(prx.proto.demo.Demo.MPCInteger32 value) {
        if (mpcI32Builder_ == null) {
          if (mpcI32_ != null) {
            mpcI32_ =
              prx.proto.demo.Demo.MPCInteger32.newBuilder(mpcI32_).mergeFrom(value).buildPartial();
          } else {
            mpcI32_ = value;
          }
          onChanged();
        } else {
          mpcI32Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public Builder clearMpcI32() {
        if (mpcI32Builder_ == null) {
          mpcI32_ = null;
          onChanged();
        } else {
          mpcI32_ = null;
          mpcI32Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32.Builder getMpcI32Builder() {
        
        onChanged();
        return getMpcI32FieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder() {
        if (mpcI32Builder_ != null) {
          return mpcI32Builder_.getMessageOrBuilder();
        } else {
          return mpcI32_ == null ?
              prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
        }
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder> 
          getMpcI32FieldBuilder() {
        if (mpcI32Builder_ == null) {
          mpcI32Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder>(
                  getMpcI32(),
                  getParentForChildren(),
                  isClean());
          mpcI32_ = null;
        }
        return mpcI32Builder_;
      }

      private prx.proto.demo.Demo.MPCFloat mpcF_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCFloat, prx.proto.demo.Demo.MPCFloat.Builder, prx.proto.demo.Demo.MPCFloatOrBuilder> mpcFBuilder_;
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public boolean hasMpcF() {
        return mpcFBuilder_ != null || mpcF_ != null;
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public prx.proto.demo.Demo.MPCFloat getMpcF() {
        if (mpcFBuilder_ == null) {
          return mpcF_ == null ? prx.proto.demo.Demo.MPCFloat.getDefaultInstance() : mpcF_;
        } else {
          return mpcFBuilder_.getMessage();
        }
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public Builder setMpcF(prx.proto.demo.Demo.MPCFloat value) {
        if (mpcFBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mpcF_ = value;
          onChanged();
        } else {
          mpcFBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public Builder setMpcF(
          prx.proto.demo.Demo.MPCFloat.Builder builderForValue) {
        if (mpcFBuilder_ == null) {
          mpcF_ = builderForValue.build();
          onChanged();
        } else {
          mpcFBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public Builder mergeMpcF(prx.proto.demo.Demo.MPCFloat value) {
        if (mpcFBuilder_ == null) {
          if (mpcF_ != null) {
            mpcF_ =
              prx.proto.demo.Demo.MPCFloat.newBuilder(mpcF_).mergeFrom(value).buildPartial();
          } else {
            mpcF_ = value;
          }
          onChanged();
        } else {
          mpcFBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public Builder clearMpcF() {
        if (mpcFBuilder_ == null) {
          mpcF_ = null;
          onChanged();
        } else {
          mpcF_ = null;
          mpcFBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public prx.proto.demo.Demo.MPCFloat.Builder getMpcFBuilder() {
        
        onChanged();
        return getMpcFFieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      public prx.proto.demo.Demo.MPCFloatOrBuilder getMpcFOrBuilder() {
        if (mpcFBuilder_ != null) {
          return mpcFBuilder_.getMessageOrBuilder();
        } else {
          return mpcF_ == null ?
              prx.proto.demo.Demo.MPCFloat.getDefaultInstance() : mpcF_;
        }
      }
      /**
       * <code>.demo.MPCFloat mpc_f = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCFloat, prx.proto.demo.Demo.MPCFloat.Builder, prx.proto.demo.Demo.MPCFloatOrBuilder> 
          getMpcFFieldBuilder() {
        if (mpcFBuilder_ == null) {
          mpcFBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              prx.proto.demo.Demo.MPCFloat, prx.proto.demo.Demo.MPCFloat.Builder, prx.proto.demo.Demo.MPCFloatOrBuilder>(
                  getMpcF(),
                  getParentForChildren(),
                  isClean());
          mpcF_ = null;
        }
        return mpcFBuilder_;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 3;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 3;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 3;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }

      private float f_ ;
      /**
       * <code>float f = 4;</code>
       */
      public float getF() {
        return f_;
      }
      /**
       * <code>float f = 4;</code>
       */
      public Builder setF(float value) {
        
        f_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float f = 4;</code>
       */
      public Builder clearF() {
        
        f_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Foo)
    }

    // @@protoc_insertion_point(class_scope:demo.Foo)
    private static final prx.proto.demo.Demo.Foo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new prx.proto.demo.Demo.Foo();
    }

    public static prx.proto.demo.Demo.Foo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Foo>
        PARSER = new com.google.protobuf.AbstractParser<Foo>() {
      @java.lang.Override
      public Foo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Foo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Foo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Foo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public prx.proto.demo.Demo.Foo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface BarOrBuilder extends
      // @@protoc_insertion_point(interface_extends:demo.Bar)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    boolean hasFoo();
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    prx.proto.demo.Demo.Foo getFoo();
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    prx.proto.demo.Demo.FooOrBuilder getFooOrBuilder();

    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    boolean hasMpcI32();
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    prx.proto.demo.Demo.MPCInteger32 getMpcI32();
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder();

    /**
     * <code>int32 i32 = 3;</code>
     */
    int getI32();
  }
  /**
   * Protobuf type {@code demo.Bar}
   */
  public  static final class Bar extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:demo.Bar)
      BarOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Bar.newBuilder() to construct.
    private Bar(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Bar() {
      i32_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Bar(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              prx.proto.demo.Demo.Foo.Builder subBuilder = null;
              if (foo_ != null) {
                subBuilder = foo_.toBuilder();
              }
              foo_ = input.readMessage(prx.proto.demo.Demo.Foo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(foo_);
                foo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              prx.proto.demo.Demo.MPCInteger32.Builder subBuilder = null;
              if (mpcI32_ != null) {
                subBuilder = mpcI32_.toBuilder();
              }
              mpcI32_ = input.readMessage(prx.proto.demo.Demo.MPCInteger32.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(mpcI32_);
                mpcI32_ = subBuilder.buildPartial();
              }

              break;
            }
            case 24: {

              i32_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return prx.proto.demo.Demo.internal_static_demo_Bar_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return prx.proto.demo.Demo.internal_static_demo_Bar_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              prx.proto.demo.Demo.Bar.class, prx.proto.demo.Demo.Bar.Builder.class);
    }

    public static final int FOO_FIELD_NUMBER = 1;
    private prx.proto.demo.Demo.Foo foo_;
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public boolean hasFoo() {
      return foo_ != null;
    }
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public prx.proto.demo.Demo.Foo getFoo() {
      return foo_ == null ? prx.proto.demo.Demo.Foo.getDefaultInstance() : foo_;
    }
    /**
     * <code>.demo.Foo foo = 1;</code>
     */
    public prx.proto.demo.Demo.FooOrBuilder getFooOrBuilder() {
      return getFoo();
    }

    public static final int MPC_I32_FIELD_NUMBER = 2;
    private prx.proto.demo.Demo.MPCInteger32 mpcI32_;
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    public boolean hasMpcI32() {
      return mpcI32_ != null;
    }
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    public prx.proto.demo.Demo.MPCInteger32 getMpcI32() {
      return mpcI32_ == null ? prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
    }
    /**
     * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
     */
    public prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder() {
      return getMpcI32();
    }

    public static final int I32_FIELD_NUMBER = 3;
    private int i32_;
    /**
     * <code>int32 i32 = 3;</code>
     */
    public int getI32() {
      return i32_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (foo_ != null) {
        output.writeMessage(1, getFoo());
      }
      if (mpcI32_ != null) {
        output.writeMessage(2, getMpcI32());
      }
      if (i32_ != 0) {
        output.writeInt32(3, i32_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (foo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getFoo());
      }
      if (mpcI32_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getMpcI32());
      }
      if (i32_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, i32_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof prx.proto.demo.Demo.Bar)) {
        return super.equals(obj);
      }
      prx.proto.demo.Demo.Bar other = (prx.proto.demo.Demo.Bar) obj;

      boolean result = true;
      result = result && (hasFoo() == other.hasFoo());
      if (hasFoo()) {
        result = result && getFoo()
            .equals(other.getFoo());
      }
      result = result && (hasMpcI32() == other.hasMpcI32());
      if (hasMpcI32()) {
        result = result && getMpcI32()
            .equals(other.getMpcI32());
      }
      result = result && (getI32()
          == other.getI32());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasFoo()) {
        hash = (37 * hash) + FOO_FIELD_NUMBER;
        hash = (53 * hash) + getFoo().hashCode();
      }
      if (hasMpcI32()) {
        hash = (37 * hash) + MPC_I32_FIELD_NUMBER;
        hash = (53 * hash) + getMpcI32().hashCode();
      }
      hash = (37 * hash) + I32_FIELD_NUMBER;
      hash = (53 * hash) + getI32();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static prx.proto.demo.Demo.Bar parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Bar parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Bar parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static prx.proto.demo.Demo.Bar parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(prx.proto.demo.Demo.Bar prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code demo.Bar}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:demo.Bar)
        prx.proto.demo.Demo.BarOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return prx.proto.demo.Demo.internal_static_demo_Bar_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return prx.proto.demo.Demo.internal_static_demo_Bar_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                prx.proto.demo.Demo.Bar.class, prx.proto.demo.Demo.Bar.Builder.class);
      }

      // Construct using prx.proto.demo.Demo.Bar.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (fooBuilder_ == null) {
          foo_ = null;
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }
        if (mpcI32Builder_ == null) {
          mpcI32_ = null;
        } else {
          mpcI32_ = null;
          mpcI32Builder_ = null;
        }
        i32_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return prx.proto.demo.Demo.internal_static_demo_Bar_descriptor;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Bar getDefaultInstanceForType() {
        return prx.proto.demo.Demo.Bar.getDefaultInstance();
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Bar build() {
        prx.proto.demo.Demo.Bar result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public prx.proto.demo.Demo.Bar buildPartial() {
        prx.proto.demo.Demo.Bar result = new prx.proto.demo.Demo.Bar(this);
        if (fooBuilder_ == null) {
          result.foo_ = foo_;
        } else {
          result.foo_ = fooBuilder_.build();
        }
        if (mpcI32Builder_ == null) {
          result.mpcI32_ = mpcI32_;
        } else {
          result.mpcI32_ = mpcI32Builder_.build();
        }
        result.i32_ = i32_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof prx.proto.demo.Demo.Bar) {
          return mergeFrom((prx.proto.demo.Demo.Bar)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(prx.proto.demo.Demo.Bar other) {
        if (other == prx.proto.demo.Demo.Bar.getDefaultInstance()) return this;
        if (other.hasFoo()) {
          mergeFoo(other.getFoo());
        }
        if (other.hasMpcI32()) {
          mergeMpcI32(other.getMpcI32());
        }
        if (other.getI32() != 0) {
          setI32(other.getI32());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        prx.proto.demo.Demo.Bar parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (prx.proto.demo.Demo.Bar) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private prx.proto.demo.Demo.Foo foo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.Foo, prx.proto.demo.Demo.Foo.Builder, prx.proto.demo.Demo.FooOrBuilder> fooBuilder_;
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public boolean hasFoo() {
        return fooBuilder_ != null || foo_ != null;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public prx.proto.demo.Demo.Foo getFoo() {
        if (fooBuilder_ == null) {
          return foo_ == null ? prx.proto.demo.Demo.Foo.getDefaultInstance() : foo_;
        } else {
          return fooBuilder_.getMessage();
        }
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder setFoo(prx.proto.demo.Demo.Foo value) {
        if (fooBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          foo_ = value;
          onChanged();
        } else {
          fooBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder setFoo(
          prx.proto.demo.Demo.Foo.Builder builderForValue) {
        if (fooBuilder_ == null) {
          foo_ = builderForValue.build();
          onChanged();
        } else {
          fooBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder mergeFoo(prx.proto.demo.Demo.Foo value) {
        if (fooBuilder_ == null) {
          if (foo_ != null) {
            foo_ =
              prx.proto.demo.Demo.Foo.newBuilder(foo_).mergeFrom(value).buildPartial();
          } else {
            foo_ = value;
          }
          onChanged();
        } else {
          fooBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public Builder clearFoo() {
        if (fooBuilder_ == null) {
          foo_ = null;
          onChanged();
        } else {
          foo_ = null;
          fooBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public prx.proto.demo.Demo.Foo.Builder getFooBuilder() {
        
        onChanged();
        return getFooFieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      public prx.proto.demo.Demo.FooOrBuilder getFooOrBuilder() {
        if (fooBuilder_ != null) {
          return fooBuilder_.getMessageOrBuilder();
        } else {
          return foo_ == null ?
              prx.proto.demo.Demo.Foo.getDefaultInstance() : foo_;
        }
      }
      /**
       * <code>.demo.Foo foo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.Foo, prx.proto.demo.Demo.Foo.Builder, prx.proto.demo.Demo.FooOrBuilder> 
          getFooFieldBuilder() {
        if (fooBuilder_ == null) {
          fooBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              prx.proto.demo.Demo.Foo, prx.proto.demo.Demo.Foo.Builder, prx.proto.demo.Demo.FooOrBuilder>(
                  getFoo(),
                  getParentForChildren(),
                  isClean());
          foo_ = null;
        }
        return fooBuilder_;
      }

      private prx.proto.demo.Demo.MPCInteger32 mpcI32_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder> mpcI32Builder_;
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public boolean hasMpcI32() {
        return mpcI32Builder_ != null || mpcI32_ != null;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32 getMpcI32() {
        if (mpcI32Builder_ == null) {
          return mpcI32_ == null ? prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
        } else {
          return mpcI32Builder_.getMessage();
        }
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public Builder setMpcI32(prx.proto.demo.Demo.MPCInteger32 value) {
        if (mpcI32Builder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          mpcI32_ = value;
          onChanged();
        } else {
          mpcI32Builder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public Builder setMpcI32(
          prx.proto.demo.Demo.MPCInteger32.Builder builderForValue) {
        if (mpcI32Builder_ == null) {
          mpcI32_ = builderForValue.build();
          onChanged();
        } else {
          mpcI32Builder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public Builder mergeMpcI32(prx.proto.demo.Demo.MPCInteger32 value) {
        if (mpcI32Builder_ == null) {
          if (mpcI32_ != null) {
            mpcI32_ =
              prx.proto.demo.Demo.MPCInteger32.newBuilder(mpcI32_).mergeFrom(value).buildPartial();
          } else {
            mpcI32_ = value;
          }
          onChanged();
        } else {
          mpcI32Builder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public Builder clearMpcI32() {
        if (mpcI32Builder_ == null) {
          mpcI32_ = null;
          onChanged();
        } else {
          mpcI32_ = null;
          mpcI32Builder_ = null;
        }

        return this;
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32.Builder getMpcI32Builder() {
        
        onChanged();
        return getMpcI32FieldBuilder().getBuilder();
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      public prx.proto.demo.Demo.MPCInteger32OrBuilder getMpcI32OrBuilder() {
        if (mpcI32Builder_ != null) {
          return mpcI32Builder_.getMessageOrBuilder();
        } else {
          return mpcI32_ == null ?
              prx.proto.demo.Demo.MPCInteger32.getDefaultInstance() : mpcI32_;
        }
      }
      /**
       * <code>.demo.MPCInteger32 mpc_i32 = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder> 
          getMpcI32FieldBuilder() {
        if (mpcI32Builder_ == null) {
          mpcI32Builder_ = new com.google.protobuf.SingleFieldBuilderV3<
              prx.proto.demo.Demo.MPCInteger32, prx.proto.demo.Demo.MPCInteger32.Builder, prx.proto.demo.Demo.MPCInteger32OrBuilder>(
                  getMpcI32(),
                  getParentForChildren(),
                  isClean());
          mpcI32_ = null;
        }
        return mpcI32Builder_;
      }

      private int i32_ ;
      /**
       * <code>int32 i32 = 3;</code>
       */
      public int getI32() {
        return i32_;
      }
      /**
       * <code>int32 i32 = 3;</code>
       */
      public Builder setI32(int value) {
        
        i32_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 i32 = 3;</code>
       */
      public Builder clearI32() {
        
        i32_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:demo.Bar)
    }

    // @@protoc_insertion_point(class_scope:demo.Bar)
    private static final prx.proto.demo.Demo.Bar DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new prx.proto.demo.Demo.Bar();
    }

    public static prx.proto.demo.Demo.Bar getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Bar>
        PARSER = new com.google.protobuf.AbstractParser<Bar>() {
      @java.lang.Override
      public Bar parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Bar(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Bar> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Bar> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public prx.proto.demo.Demo.Bar getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_MPCInteger32_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_MPCInteger32_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_MPCFloat_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_MPCFloat_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Foo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Foo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_demo_Bar_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_demo_Bar_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ndemo.proto\022\004demo\"\033\n\014MPCInteger32\022\013\n\003i3" +
      "2\030\001 \001(\005\"\025\n\010MPCFloat\022\t\n\001f\030\001 \001(\002\"a\n\003Foo\022#\n" +
      "\007mpc_i32\030\001 \001(\0132\022.demo.MPCInteger32\022\035\n\005mp" +
      "c_f\030\002 \001(\0132\016.demo.MPCFloat\022\013\n\003i32\030\003 \001(\005\022\t" +
      "\n\001f\030\004 \001(\002\"O\n\003Bar\022\026\n\003foo\030\001 \001(\0132\t.demo.Foo" +
      "\022#\n\007mpc_i32\030\002 \001(\0132\022.demo.MPCInteger32\022\013\n" +
      "\003i32\030\003 \001(\005B\020\n\016prx.proto.demob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_demo_MPCInteger32_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_demo_MPCInteger32_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_MPCInteger32_descriptor,
        new java.lang.String[] { "I32", });
    internal_static_demo_MPCFloat_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_demo_MPCFloat_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_MPCFloat_descriptor,
        new java.lang.String[] { "F", });
    internal_static_demo_Foo_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_demo_Foo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Foo_descriptor,
        new java.lang.String[] { "MpcI32", "MpcF", "I32", "F", });
    internal_static_demo_Bar_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_demo_Bar_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_demo_Bar_descriptor,
        new java.lang.String[] { "Foo", "MpcI32", "I32", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
